version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JAVA_OPTS: -Xmx256m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run:
          name: Fetch dependencies
          command: ./gradlew --no-daemon -Pci dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Run all tests and checks
          command: ./gradlew --no-daemon -Pci check

      - run:
          name: Compile JMH benchmark sources
          command: ./gradlew --no-daemon -Pci :testware:performance-tests:jmhClasses

      - run:
          name: Collect test result files in single folder
          when: always
          command: |
              mkdir -p build/junit/
              cp `find . -name "*.xml" | grep "build/test-results/test/"` build/junit/

      - store_test_results:
          path: ~/repo/build/junit


  tck:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx256m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run:
          name: Fetch dependencies
          command: ./gradlew --no-daemon -Pci dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Run OpenCypher TCK tests
          command: ./gradlew --no-daemon -Pci tck

      - store_test_results:
          path: ~/repo/testware/tck/build/test-results

      - store_artifacts:
          path: ~/repo/testware/tck/build/test-results/tck/TEST-org.opencypher.gremlin.tck.TckTest.xml

      - store_artifacts:
          path: ~/repo/testware/tck/build/reports/tests/cucumber/cucumber-html-reports

      - run:
          # CircleCI hack: print variable to a file because using env variable as cache key is not supported.
          name: Get base commit hash
          command: |
            export BASE_COMMIT=$(git merge-base remotes/origin/master ${CIRCLE_BRANCH})
            echo $BASE_COMMIT > ~/.base-commit.txt
            echo $BASE_COMMIT

      - restore_cache:
          keys:
          - v1-tck-master-{{ checksum "~/.base-commit.txt" }}

      - run:
          name: Compare TCK results with master branch
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              ./gradlew --no-daemon -Pci tckRegression
            fi

      - store_artifacts:
          path: ~/repo/testware/tck/build/reports/tests/regression.html

      - run:
          name: Save TCK report
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./gradlew --no-daemon -Pci tckSaveReport
            fi

      - save_cache:
          paths:
            - ~/repo/testware/tck/build/test-results/tck/TckTest-before.xml
          key: v1-tck-{{ .Branch }}-{{ checksum "~/.base-commit.txt" }}


workflows:
  version: 2
  build_and_tck:
    jobs:
      - build
      - tck:
          requires:
            - build

experimental:
  notify:
    branches:
      only:
        - master
